services:
  api:
    build: .
    volumes:
      - .:/var/task
    working_dir: /var/task
    ports:
      - "8000:8000"
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
    environment:
      - HOME=/tmp
      - PYTHONPATH=/var/task 
    command: ["uvicorn", "app.main:app", "--reload", "--host=0.0.0.0"]
    entrypoint: ['poetry', 'run']
    depends_on:
      - db

  db:
    image: postgres:14.10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '4000:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5000:80'
    depends_on:
      - db
    logging:
      driver: none

volumes:
  db-data:
    driver: local