# version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped
    container_name: pgadmin
    depends_on:
      - postgres-service
    networks:
      - hedjobs
    ports:
      - '5000:80'

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi
    container_name: fastapi
    restart: unless-stopped
    depends_on:
      - postgres-service
    ports:
      - '8000:8000'
    networks:
      - hedjobs
    volumes:
      - '.:/usr/srv'

  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtp
    networks:
      - hedjobs
    ports:
      - '8025:8025'
      - '1025:1025'

  postgres-service:
    image: postgres:14.10-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '4000:5432'
    networks:
      - hedjobs
    volumes:
      - hedjobs_postgres_data:/var/lib/postgres

  minio-service:
    image: minio/minio
    restart: unless-stopped
    container_name: minio
    command: minio server --console-address ":9090" /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9090:9090'
    networks:
      - hedjobs
    volumes:
      - minio-data:/data

networks:
  hedjobs:
volumes:
  hedjobs_postgres_data:
    driver: local
  minio-data:
    driver: local