INSERT INTO m_skill (skill_name, created_at, updated_at)
VALUES
('Python', now(), now()),
('JavaScript', now(), now()),
('SQL', now(), now()),
('HTML', now(), now()),
('CSS', now(), now()),
('React', now(), now()),
('Angular', now(), now()),
('Java', now(), now()),
('C#', now(), now()),
('PHP', now(), now()),
('Ruby', now(), now()),
('Node.js', now(), now()),
('Swift', now(), now()),
('Objective-C', now(), now()),
('TypeScript', now(), now()),
('Kotlin', now(), now()),
('Perl', now(), now()),
('R', now(), now()),
('Scala', now(), now()),
('Go', now(), now()),
('Assembly', now(), now()),
('VB.NET', now(), now()),
('Shell Scripting', now(), now()),
('Matlab', now(), now()),
('Fortran', now(), now()),
('COBOL', now(), now()),
('Haskell', now(), now()),
('Lua', now(), now()),
('Groovy', now(), now()),
('Dart', now(), now()),
('Rust', now(), now()),
('Julia', now(), now()),
('Pascal', now(), now()),
('Scheme', now(), now()),
('Ada', now(), now()),
('F#', now(), now()),
('Erlang', now(), now()),
('Clojure', now(), now()),
('Prolog', now(), now()),
('Smalltalk', now(), now()),
('Delphi', now(), now()),
('LabVIEW', now(), now()),
('Verilog', now(), now()),
('VHDL', now(), now()),
('PL/SQL', now(), now()),
('T-SQL', now(), now()),
('Bash', now(), now()),
('PowerShell', now(), now()),
('XML', now(), now()),
('JSON', now(), now()),
('YAML', now(), now()),
('GraphQL', now(), now()),
('REST', now(), now()),
('SOAP', now(), now()),
('Spring Framework', now(), now()),
('Hibernate', now(), now()),
('Flask', now(), now()),
('Django', now(), now()),
('Express.js', now(), now()),
('Vue.js', now(), now()),
('Ember.js', now(), now()),
('Redux', now(), now()),
('RxJS', now(), now()),
('jQuery', now(), now()),
('Bootstrap', now(), now()),
('Foundation', now(), now()),
('Semantic UI', now(), now()),
('Material UI', now(), now()),
('Sass', now(), now()),
('Less', now(), now()),
('Webpack', now(), now()),
('Gulp', now(), now()),
('Grunt', now(), now()),
('Docker', now(), now()),
('Kubernetes', now(), now()),
('AWS', now(), now()),
('Azure', now(), now()),
('Google Cloud Platform', now(), now()),
('Firebase', now(), now()),
('Jenkins', now(), now()),
('CircleCI', now(), now()),
('Git', now(), now()),
('SVN', now(), now()),
('Mercurial', now(), now()),
('JIRA', now(), now()),
('Confluence', now(), now()),
('Slack', now(), now()),
('Trello', now(), now()),
('Asana', now(), now()),
('Zendesk', now(), now()),
('Salesforce', now(), now()),
('Zendesk', now(), now()),
('ServiceNow', now(), now()),
('ERP Systems', now(), now()),
('CRM Systems', now(), now()),
('BI Tools', now(), now()),
('Big Data', now(), now()),
('Data Warehousing', now(), now()),
('Machine Learning', now(), now()),
('Deep Learning', now(), now()),
('Natural Language Processing', now(), now()),
('Computer Vision', now(), now()),
('Blockchain', now(), now()),
('Cryptocurrency', now(), now()),
('Cybersecurity', now(), now()),
('Network Administration', now(), now()),
('Systems Administration', now(), now()),
('DevOps', now(), now()),
('Agile Methodologies', now(), now()),
('Scrum', now(), now()),
('Kanban', now(), now());